export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_QTY = 'INCREASE_QTY';
export const DECREASE_QTY = 'DECREASE_QTY';
export const DELETE_CART = 'DELETE_CART';
export const DELETE_ALL_CART = 'DELETE_ALL_CART';

export const ALL_COMMENTS_SUCCESS = 'ALL_COMMENTS_SUCCESS';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const COMMENTS_ERROR = 'COMMENTS_ERROR';
export const LOADING_COMMENTS = 'LOADING_COMMENTS';

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const GET_PRODUCTS_BY_ORDER_ID_SUCCESS = 'GET_PRODUCTS_BY_ORDER_ID_SUCCESS';
export const ORDERED_PRODUCTS_ERROR = 'ORDERED_PRODUCTS_ERROR';

export const LOADING_ORDERS = 'LOADING_ORDERS';
export const POST_ORDERS_SUCCESS = 'POST_ORDERS_SUCCESS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const ORDERS_ERROR = 'ORDERS_ERROR';
export const UPDATE_ORDER = 'UPDATE_ORDER'

export const FETCH_PRODUCTS_LOADING = 'FETCH_PRODUCTS_LOADING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const LOADING_USERS = 'LOADING_USERS';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_ERRORS = 'USERS_ERRORS';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';